// Mocks generated by Mockito 5.4.6 from annotations
// in front/test/data/remote/services/vk_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:front/data/local/prefs_storage.dart' as _i4;
import 'package:front/data/remote/api/vk_api_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVkAudioResponse_0 extends _i1.SmartFake
    implements _i2.VkAudioResponse {
  _FakeVkAudioResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVkArtistResponse_1 extends _i1.SmartFake
    implements _i2.VkArtistResponse {
  _FakeVkArtistResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VkApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockVkApiClient extends _i1.Mock implements _i2.VkApiClient {
  MockVkApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.VkAudioResponse> getAudioById({
    required String? audios,
    required String? accessToken,
    String? version = '5.131',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAudioById, [], {
              #audios: audios,
              #accessToken: accessToken,
              #version: version,
            }),
            returnValue: _i3.Future<_i2.VkAudioResponse>.value(
              _FakeVkAudioResponse_0(
                this,
                Invocation.method(#getAudioById, [], {
                  #audios: audios,
                  #accessToken: accessToken,
                  #version: version,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.VkAudioResponse>);

  @override
  _i3.Future<_i2.VkArtistResponse> getArtistById({
    required String? artistId,
    required String? accessToken,
    String? version = '5.131',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getArtistById, [], {
              #artistId: artistId,
              #accessToken: accessToken,
              #version: version,
            }),
            returnValue: _i3.Future<_i2.VkArtistResponse>.value(
              _FakeVkArtistResponse_1(
                this,
                Invocation.method(#getArtistById, [], {
                  #artistId: artistId,
                  #accessToken: accessToken,
                  #version: version,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.VkArtistResponse>);
}

/// A class which mocks [PrefsStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrefsStorage extends _i1.Mock implements _i4.PrefsStorage {
  MockPrefsStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveTokenExpiry(DateTime? expiresAt) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokenExpiry, [expiresAt]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveVkAppId(String? vkAppId) =>
      (super.noSuchMethod(
            Invocation.method(#saveVkAppId, [vkAppId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearVkAppId() =>
      (super.noSuchMethod(
            Invocation.method(#clearVkAppId, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
