// Mocks generated by Mockito 5.4.6 from annotations
// in front/test/domain/repositories/audio_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:fast_immutable_collections/fast_immutable_collections.dart'
    as _i4;
import 'package:front/data/local/audio_storage/audio_storage.dart' as _i6;
import 'package:front/data/local/audio_storage/drift/database.dart' as _i8;
import 'package:front/data/remote/api/filtered_track_sessions_client.dart'
    as _i9;
import 'package:front/data/remote/api/vk_api_client.dart' as _i3;
import 'package:front/data/remote/services/vk_service.dart' as _i2;
import 'package:front/domain/entities/track_session.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeVkAudioResult_0 extends _i1.SmartFake implements _i2.VkAudioResult {
  _FakeVkAudioResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVkArtistInfo_1 extends _i1.SmartFake implements _i3.VkArtistInfo {
  _FakeVkArtistInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIList_2<T> extends _i1.SmartFake implements _i4.IList<T> {
  _FakeIList_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString([bool? prettyPrint]) => super.toString();
}

/// A class which mocks [VkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVkService extends _i1.Mock implements _i2.VkService {
  MockVkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.VkAudioResult> getAudioById(_i4.IList<String>? audioIds) =>
      (super.noSuchMethod(
            Invocation.method(#getAudioById, [audioIds]),
            returnValue: _i5.Future<_i2.VkAudioResult>.value(
              _FakeVkAudioResult_0(
                this,
                Invocation.method(#getAudioById, [audioIds]),
              ),
            ),
          )
          as _i5.Future<_i2.VkAudioResult>);

  @override
  _i5.Future<_i3.VkArtistInfo> getArtistById(String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#getArtistById, [artistId]),
            returnValue: _i5.Future<_i3.VkArtistInfo>.value(
              _FakeVkArtistInfo_1(
                this,
                Invocation.method(#getArtistById, [artistId]),
              ),
            ),
          )
          as _i5.Future<_i3.VkArtistInfo>);
}

/// A class which mocks [AudioStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioStorage extends _i1.Mock implements _i6.AudioStorage {
  MockAudioStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.IList<_i3.VkAudioTrack>> getTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getTracks, []),
            returnValue: _i5.Future<_i4.IList<_i3.VkAudioTrack>>.value(
              _FakeIList_2<_i3.VkAudioTrack>(
                this,
                Invocation.method(#getTracks, []),
              ),
            ),
          )
          as _i5.Future<_i4.IList<_i3.VkAudioTrack>>);

  @override
  _i5.Future<void> updateTracks(_i4.IList<_i3.VkAudioTrack>? tracks) =>
      (super.noSuchMethod(
            Invocation.method(#updateTracks, [tracks]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAllTracks() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllTracks, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isTrackUnavailable(int? id, int? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#isTrackUnavailable, [id, ownerId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> markTrackAsUnavailable(
    int? id,
    int? ownerId,
    String? fullId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markTrackAsUnavailable, [id, ownerId, fullId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> getUnavailableTracksCount({
    _i4.IList<_i7.TrackSession>? sessions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUnavailableTracksCount, [], {
              #sessions: sessions,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i4.IList<_i8.UnavailableTrack>> getUnavailableTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getUnavailableTracks, []),
            returnValue: _i5.Future<_i4.IList<_i8.UnavailableTrack>>.value(
              _FakeIList_2<_i8.UnavailableTrack>(
                this,
                Invocation.method(#getUnavailableTracks, []),
              ),
            ),
          )
          as _i5.Future<_i4.IList<_i8.UnavailableTrack>>);

  @override
  _i5.Future<void> clearUnavailableTracks() =>
      (super.noSuchMethod(
            Invocation.method(#clearUnavailableTracks, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.VkArtist?> getCachedArtist(String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedArtist, [artistId]),
            returnValue: _i5.Future<_i3.VkArtist?>.value(),
          )
          as _i5.Future<_i3.VkArtist?>);

  @override
  _i5.Future<void> saveCachedArtist(_i3.VkArtist? artist, String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#saveCachedArtist, [artist, artistId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i4.IList<_i3.VkArtist>> getAllCachedArtists() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCachedArtists, []),
            returnValue: _i5.Future<_i4.IList<_i3.VkArtist>>.value(
              _FakeIList_2<_i3.VkArtist>(
                this,
                Invocation.method(#getAllCachedArtists, []),
              ),
            ),
          )
          as _i5.Future<_i4.IList<_i3.VkArtist>>);

  @override
  _i5.Future<bool> isArtistPhotoChecked(String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#isArtistPhotoChecked, [artistId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> markArtistPhotoChecked(String? artistId, bool? hasPhoto) =>
      (super.noSuchMethod(
            Invocation.method(#markArtistPhotoChecked, [artistId, hasPhoto]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i4.IList<String>> getArtistsToUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#getArtistsToUpdate, []),
            returnValue: _i5.Future<_i4.IList<String>>.value(
              _FakeIList_2<String>(
                this,
                Invocation.method(#getArtistsToUpdate, []),
              ),
            ),
          )
          as _i5.Future<_i4.IList<String>>);
}

/// A class which mocks [FilteredTrackSessionsClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilteredTrackSessionsClient extends _i1.Mock
    implements _i9.FilteredTrackSessionsClient {
  MockFilteredTrackSessionsClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.IList<_i7.TrackSession>> getSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getSessions, []),
            returnValue: _i5.Future<_i4.IList<_i7.TrackSession>>.value(
              _FakeIList_2<_i7.TrackSession>(
                this,
                Invocation.method(#getSessions, []),
              ),
            ),
          )
          as _i5.Future<_i4.IList<_i7.TrackSession>>);
}
