// Mocks generated by Mockito 5.4.6 from annotations
// in front/test/domain/services/statistics_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fast_immutable_collections/fast_immutable_collections.dart'
    as _i2;
import 'package:front/data/local/audio_storage/audio_storage.dart' as _i3;
import 'package:front/data/local/audio_storage/drift/database.dart' as _i6;
import 'package:front/data/remote/api/vk_api_client.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIList_0<T> extends _i1.SmartFake implements _i2.IList<T> {
  _FakeIList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString([bool? prettyPrint]) => super.toString();
}

/// A class which mocks [AudioStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioStorage extends _i1.Mock implements _i3.AudioStorage {
  MockAudioStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.IList<_i5.VkAudioTrack>> getTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getTracks, []),
            returnValue: _i4.Future<_i2.IList<_i5.VkAudioTrack>>.value(
              _FakeIList_0<_i5.VkAudioTrack>(
                this,
                Invocation.method(#getTracks, []),
              ),
            ),
          )
          as _i4.Future<_i2.IList<_i5.VkAudioTrack>>);

  @override
  _i4.Future<void> updateTracks(_i2.IList<_i5.VkAudioTrack>? tracks) =>
      (super.noSuchMethod(
            Invocation.method(#updateTracks, [tracks]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllTracks() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllTracks, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isTrackUnavailable(int? id, int? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#isTrackUnavailable, [id, ownerId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> markTrackAsUnavailable(
    int? id,
    int? ownerId,
    String? fullId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markTrackAsUnavailable, [id, ownerId, fullId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getUnavailableTracksCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnavailableTracksCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i2.IList<_i6.UnavailableTrack>> getUnavailableTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getUnavailableTracks, []),
            returnValue: _i4.Future<_i2.IList<_i6.UnavailableTrack>>.value(
              _FakeIList_0<_i6.UnavailableTrack>(
                this,
                Invocation.method(#getUnavailableTracks, []),
              ),
            ),
          )
          as _i4.Future<_i2.IList<_i6.UnavailableTrack>>);

  @override
  _i4.Future<void> clearUnavailableTracks() =>
      (super.noSuchMethod(
            Invocation.method(#clearUnavailableTracks, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
