// Mocks generated by Mockito 5.4.6 from annotations
// in front/test/integration_test/mocks/cache_service_interface_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:front/domain/entities/audio_track.dart' as _i4;
import 'package:front/domain/services/cache_service_interface.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CacheServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheServiceInterface extends _i1.Mock
    implements _i2.CacheServiceInterface {
  MockCacheServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cacheTracks(List<_i4.AudioTrack>? tracks) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTracks, [tracks]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.AudioTrack>> getCachedTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTracks, []),
            returnValue: _i3.Future<List<_i4.AudioTrack>>.value(
              <_i4.AudioTrack>[],
            ),
          )
          as _i3.Future<List<_i4.AudioTrack>>);

  @override
  _i3.Future<void> cacheStatistics(
    String? key,
    Map<String, dynamic>? statistics,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheStatistics, [key, statistics]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getCachedStatistics(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedStatistics, [key]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> hasToken() =>
      (super.noSuchMethod(
            Invocation.method(#hasToken, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isCacheStale() =>
      (super.noSuchMethod(
            Invocation.method(#isCacheStale, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<DateTime?> getLastCacheUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#getLastCacheUpdate, []),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);
}
