// Mocks generated by Mockito 5.4.6 from annotations
// in front/test/integration_test/mocks/vk_api_service_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:front/data/services/vk_api_service.dart' as _i2;
import 'package:front/domain/entities/audio_track.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [VkApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVkApiService extends _i1.Mock implements _i2.VkApiService {
  MockVkApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setToken(String? token) => super.noSuchMethod(
    Invocation.method(#setToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<List<_i4.AudioTrack>> getAudioById(List<String>? audioIds) =>
      (super.noSuchMethod(
            Invocation.method(#getAudioById, [audioIds]),
            returnValue: _i3.Future<List<_i4.AudioTrack>>.value(
              <_i4.AudioTrack>[],
            ),
          )
          as _i3.Future<List<_i4.AudioTrack>>);

  @override
  _i3.Future<_i4.AudioTrack?> getSingleAudioById(String? audioId) =>
      (super.noSuchMethod(
            Invocation.method(#getSingleAudioById, [audioId]),
            returnValue: _i3.Future<_i4.AudioTrack?>.value(),
          )
          as _i3.Future<_i4.AudioTrack?>);

  @override
  _i3.Future<List<_i4.AudioTrack>> getUserAudio({int? count, int? offset}) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAudio, [], {
              #count: count,
              #offset: offset,
            }),
            returnValue: _i3.Future<List<_i4.AudioTrack>>.value(
              <_i4.AudioTrack>[],
            ),
          )
          as _i3.Future<List<_i4.AudioTrack>>);

  @override
  _i3.Future<List<_i4.AudioTrack>> getPopularAudio({int? count, int? offset}) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularAudio, [], {
              #count: count,
              #offset: offset,
            }),
            returnValue: _i3.Future<List<_i4.AudioTrack>>.value(
              <_i4.AudioTrack>[],
            ),
          )
          as _i3.Future<List<_i4.AudioTrack>>);
}
