name: front
description: VK Wrapped - статистика прослушивания музыки
publish_to: 'none'
version: 1.10.1+110
environment:
  sdk: ^3.8.1
  flutter: ^3.32.5
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  bloc_presentation: ^1.1.1
  cupertino_icons: ^1.0.2
  sprintf: ^7.0.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  bloc_concurrency: ^0.3.0
  flutter_slidable: ^4.0.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.2
  share_plus: ^11.0.0
  rxdart: ^0.28.0
  path_provider: ^2.1.1
  meta: ^1.16.0
  logger: ^2.6.0
  collection: ^1.17.0
  dotted_line: ^3.2.2
  theme_tailor_annotation: ^3.0.1
  freezed_annotation: ^3.0.0
  dartx: ^1.2.0
  fast_immutable_collections: ^11.0.4
  injectable:
    git:
      url: https://github.com/ChaserVasya/injectable
      ref: synced-with-retrofit-1
      path: injectable
  retrofit:
    git:
      url: https://github.com/ChaserVasya/retrofit.dart
      ref: synced-with-injectable-1.2
      path: retrofit
  get_it: ^8.0.3
  auto_route: ^10.1.0+1
  dio: ^5.3.3
  json_annotation: ^4.9.0
  gap: ^3.0.1
  sliver_tools: ^0.2.12
  pull_down_button: ^0.10.1
  intl: ^0.20.2
  clock: ^1.1.1
  bloc_event_transformers: ^2.0.0
  slivers: ^0.0.1+2
  convert: ^3.1.1
  bubble: ^1.2.1
  table_sticky_headers: ^2.0.5
  dio_smart_retry: ^7.0.1
  dio_cache_interceptor: ^3.5.0

  permission_handler: ^12.0.0+1
  shimmer: ^3.0.0
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.20
  path: ^1.9.1
  pretty_dio_logger: ^1.4.0
  flutter_native_splash: ^2.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  melos: ^6.1.0
  mockito: ^5.4.6
  http_mock_adapter: ^0.6.1
  flutter_gen_runner: ^5.3.2
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  injectable_generator:
    git:
      url: https://github.com/ChaserVasya/injectable
      ref: synced-with-retrofit-1
      path: injectable_generator
  retrofit_generator:
    git:
      url: https://github.com/ChaserVasya/retrofit.dart
      ref: synced-with-injectable-1.2
      path: generator
  build_runner: ^2.4.15
  auto_route_generator: ^10.1.0
  test: ^1.25.15
  yaml: ^3.1.3
  drift_dev: ^2.26.0
flutter_gen:
  output: lib/ui/resources/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_icon.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app_icon.jpg"
  remove_alpha_ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/memes/
